matuzo/HTMHell

hell/_data/authors.js, hell/entries/4_link_and_button.md
Signed-off-by: Hidde de Vries <hidde@hiddedevries.nl>
=> [draft] Add button and link example

.eleventy.js, hell/_includes/layouts/base.njk, hell/favicon/site.webmanifest, package.json
Hello, thank you of awesome website :)
During browsing the website I've got an idea – it will be nice to access it offline. I've checked 11ty way and found nice plugin which adds basic PWA support.
Hope it will be usable, have a nice day :)
=> Basic PWA support

hell/adventcalendar/2022/16.md
Just updating based on something I saw from Sara on Twitter and confirmed with some testing on a recent project. Happy to try and find a better link if a Twitter thread isn't the best place to send people. Tried to add a disclaimer to make it clear as realise not everybody might want to be taken there!
=> fix: #16 update - list role note for nav landmark

hell/adventcalendar/2022/16.md
- Complete web.dev courses now available, so removed caveat notes
- Saw a great article from Ben Myers from a couple of years back on button functionality being attached to non-interactive elements
=> chore: article 16 - further reading/help link updates

hell/adventcalendar/2023/7.md
I accidentally committed to review2023 with my past commit, sorry about that. Using this PR to indicate I'm review complete.
=> [Eric review] Update 7.md

hell/adventcalendar/2023/14.md
@matuzo A note here that the LiveCodes embed is a focus trap, and we'll want skiplinks set up as a bypass mechanism.
=> [Eric review] #14

hell/adventcalendar/2023/16.md
I'm not going to sign up to a service to review a single blog post, but I'm happy to review it once it's been converted to Markdown and added over here.
=> [Eric review] Skipping #16

hell/adventcalendar/2023/22.md
=> [Eric review] #22

hell/adventcalendar/2023/8/index.md
I applied most of the suggestions, apart from the last one. I’ll need some time to come up with a different conclusion.
Meanwhile, you can review the rest :)
Speaking of the `<marquee>`, how about some inline JS and stop/start buttons?
=> Update article “The road to HTMHell”

hell/adventcalendar/2023/20.md
Thanks for your review and feedback! Here's my updated article.
=> Update article "Never underestimate HTML" according to review

hell/adventcalendar/2023/10.md
I've added most of the suggested changes to make the article more clear. Also, the article clearly wasn't finished, so I worked on making the article more rounded.
=> Review2023 - Revision of the Slots article

hell/adventcalendar/2023/8/index.md
I hope it’s fine now and not too late.
=> Update conclusion and bio for “The road to HTMHell”

hell/adventcalendar/2023/2.md
=> Fix type in 2.md

hell/adventcalendar/2023/4.md
I left comments under each of the review comments. Let me know if everything is looking ok.
Thanks!
=> Updated based on review

hell/adventcalendar/2023/12.md
I've tried to incorporate the feedback to my best ability. 
Let me know if any further adjustments are needed. I'll try to keep an extra eye on this during the weekend.
=> Adjustments for post Swallowing camels

hell/adventcalendar/2023/2.md
@matuzo I have incorporated the review comments. Thank you
=> Update review comments

hell/adventcalendar/2023/18/index.md
=> fix 2023-18 typo

hell/adventcalendar/2024/2/index.md
Add the article on `autofocus`.
=> Add autofocus article

hell/adventcalendar/2024/24/index.md
Here it is! I've added an easter egg to give a clue where this bad code comes from, let's see if you can find it. 😈
=> O label where art thou

hell/entries/34-a-button-is-not-a-link.md
A very small one, but I’d like to hear what you think.
=> New article

hell/adventcalendar/2024/10/index.md
Thanks for the feedback. I added the CodePen examples as suggested. I also added some findings about the origins of the "weird" behavior as well as a bonus fact about Android. I removed the example on how to disable submit on enter because I found it's out of scope.
=> Work in 2024-10 advent calendar article feedback.

hell/adventcalendar/2024/2/index.md
I noticed an unfinished sentence in my article, so here's the missing bit.
=> Finish my own sentence

hell/adventcalendar/2024/23/index.md
Updating article after first round of feedback
=> Advent 2024 - Day 23

hell/adventcalendar/2024/14/index.md
hello,
thank you very much for reviewing my post. I read through your feedback very carefully and have now reviewed it.
I really appreciate about your feedback. 
I currently have the time to include your feedback as quickly as possible.
PS: I hope the formatting of the post didn't break because I added the changes via the GitHub interface.
=> Update Advent24 day14: Page by Page: How Pagination Makes the Web Accessible

hell/adventcalendar/index.njk
Add a link to the list at the bottom of the page
=> Add link to HTMHell Advent calendar 2023

hell/adventcalendar/2024/26/index.md
Thank you for the feedback!
- Added screen reader testing information
- Added links to top HTML elements
- Revised intro sentence
- Revised topmatter
Let me know if there is anything else I can provide.
=> Revise advent 2024 article 26

hell/adventcalendar/2024/27/index.md
Adjustments based on the comments from @matuzo.
=> Adjustments to advent calendar article 27

hell/adventcalendar/2024/28/index.md
I wrote HTML headers but meant HTTP headers.
=> Fixes a typo
